source 'https://rubygems.org'

gem 'sinatra', '~> 2.2', '>= 2.2.3'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'config', '~> 1.0', '>= 1.0.0'
gem 'blockchain', '~> 3.0.1', '>= 1.1.1'
gem 'shotgun', '~> 0.9.1'
